dist: xenial
language: clojure
lein: lein
jdk:
    - openjdk8
    - openjdk11
    - openjdk13
    - openjdk15
jobs: 
    include:
        - stage: lint
          script: lein lint
        - stage: build
          script: lein javac
        - stage: test
          script: lein do clean, javac, test
after_success:
    - bash -ex test/coveralls.sh
notifications:
  recipients:
    - ido@appsflyer.com
    - avi.rogalsky@appsflyer.com
