dist: xenial
sudo: required
language: clojure
lein: lein
after_script:
  - bash -ex test/coveralls.sh
jobs:
  include:
    - stage: lint
      script: lein clj-kondo --lint src test --cache false
    - stage: test
      script: lein eftest
notifications:
  recipients:
    - ido@appsflyer.com
    - avi.rogalsky@appsflyer.com
