dist: xenial
sudo: required
language: clojure
lein: lein
after_script:
  - bash -ex test/coveralls.sh
script: lein do clean, javac, test
notifications:
  recipients:
    - ido@appsflyer.com
    - avi.rogalsky@appsflyer.com
