dist: xenial
language: clojure
lein: lein2
jdk:
    - openjdk8
    - openjdk11
    - openjdk13
    - openjdk15
after_script:
  - bash -ex test/coveralls.sh
jobs: 
    include:
        - stage: lint
          script: lein lint
        - stage: build
          script: lein do javac
        - stage: test
          script: lein do clean, javac, test
notifications:
  recipients:
    - ido@appsflyer.com
    - avi.rogalsky@appsflyer.com
