name: "Pull Request Build & Test"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Restore local Maven repository from cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles( 'project.clj' ) }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Validate SNAPSHOT version
        env:
          SNAPSHOT_REGEX: ^[0-9]{1,2}[.][0-9]{1,2}[.][0-9]{1,3}-SNAPSHOT$
        if: github.ref != 'refs/heads/master'
        run: |
          lein pom
          export VERSION=$(less pom.xml | grep "<version>" | head -1 | cut -d ">" -f2 | cut -d "<" -f1)
          echo "Version is:" $VERSION
          if [[ !("$VERSION" =~ $SNAPSHOT_REGEX) ]]
          then
            echo "Version isn't a SNAPSHOT version:" $VERSION
            exit 0
          fi
      - name: lint
        run: lein lint

  test:
    needs: build
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Restore local Maven repository from cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles( 'project.clj' ) }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Unit and integration tests
        run: lein test :all
